version: '3.7'

services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_DC=datacenter1
    volumes:
      - ./cassandra_data:/var/lib/cassandra

